server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/drdo_poc
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

logging.level.com.mydummyapp=INFO
